# Generated by Django 3.1.5 on 2021-01-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(blank=True, help_text='The view where the message was submitted from.', max_length=128)),
                ('message', models.CharField(blank=True, help_text='The actual text of the message.', max_length=2048)),
                ('level', models.IntegerField(help_text='An integer describing the type of the message.')),
                ('seen_at', models.DateTimeField(blank=True, default=None, help_text='When the message was seen.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The session where the message was submitted to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sessions.session')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Custom tags for the message.', max_length=2048)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_tags', to='drf_messages.message')),
            ],
        ),
    ]
