name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release-* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "2.2"  # LTS
          - "3.0"
          - "3.1"
          - "3.2"  # LTS
          - "4.0"
        exclude:
          # Python 3.9 is compatible with django 3.0+
          - python-version: "3.9"
            django-version: "2.2"
          # Python 3.10 is compatible with Django 3.2+
          - python-version: "3.10"
            django-version: "2.2"
          - python-version: "3.10"
            django-version: "3.0"
          - python-version: "3.10"
            django-version: "3.1"
          # Django 4 is compatible with Python 3.8+
          - python-version: "3.7"
            django-version: "4.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: python -m pip install -U pip

      - name: Install Dependencies
        working-directory: ./testproj
        run: pip install -r requirements-github.txt

      - name: Upgrade django version
        run: python -m pip install "Django~=${{ matrix.django-version }}.0"

      - name: Python and Django versions
        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"

      - name: Make logs directory
        working-directory: ./testproj
        run: mkdir logs
          
      - name: Run Tests
        working-directory: ./testproj
        run: python manage.py test
