name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "drf_messages testproj"
        use-pylint: true
        use-pycodestyle: true
        use-flake8: true
        use-black: true
        use-mypy: true
        use-isort: true
